<a href="https://colab.research.google.com/github/tummalapallimurali/GenAI/blob/main/Hopfield_and_BAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 4: Use the bipolar input patterns A, D and H from Project 3.4 (on page 154).  \
(a) Create an autoassociative Hopfield network and train on these three patterns (15 inputs). \
(b) Test the recall on the same three patterns.  What are your conclusions?\
(c) Edit the patterns to become slightly and then severely corrupted (bits switched).  Test the recall of your Hopfield network on these corrupted A, D, and H patterns.  What are your conclusions?  What is the relationship of Hamming distance to classification accuracy?


In [ ]:
import numpy as np

def weights(A, D):
    W = np.outer(A, A) + np.outer(D, D)
    np.fill_diagonal(W, 0)
    return W

def update_pattern(input_pattern, B):
    A = input_pattern.copy()
    for i in range(len(input_pattern)):
        net = A @ B[:, i] + A[i]
        A[i] = -1 if net < 0 else 1
    return A

def check_convergence(input_pattern, B):
    A = update_pattern(input_pattern, B)
    if np.array_equal(input_pattern, A):
        print("Pattern converged to a stable state")
        return True
    else:
        print("Pattern did not converge to a stable state, repeat another iteration")
        return False

# Test the energy function
def energy(state, weights):
    return -0.5 * np.sum(weights * np.outer(state, state))



In [ ]:
import numpy as np

input_A  = np.array([-1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1])
target_A = np.array([-1, -1, -1])

input_D = np.array([1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1])
target_D = np.array([-1, 1, 1])

input_H = np.array([1, -1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1])
target_H = np.array([1, 1, 1])

# Corrupted version of input A
input_A_corrupted = np.array([-1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1])

# Corrupted version of input D
input_D_corrupted = np.array([1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1])

# Corrupted version of input H
input_H_corrupted = np.array([1, -1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1])

# Combine input patterns into a list
input_patterns = [input_A, input_D, input_H]
target_patterns = [target_A, target_D, target_H]

# Initialize weight matrix
num_neurons = len(input_A)
weights = np.zeros((num_neurons, num_neurons))

# Train the network using the outer product
for pattern in input_patterns:
    weights += np.outer(pattern, pattern)

# Ensure no self-connections
np.fill_diagonal(weights, 0)

print("Weight matrix:\n", weights)

Weight matrix:
 [[ 0. -1.  1.  1. -1.  1.  1. -1.  1.  1. -1.  1.  1.  1. -1.]
 [-1.  0. -3.  1. -1.  1.  1. -1.  1.  1. -1.  1.  1.  1. -1.]
 [ 1. -3.  0. -1.  1. -1. -1.  1. -1. -1.  1. -1. -1. -1.  1.]
 [ 1.  1. -1.  0. -3.  3.  3.  1.  3.  3. -3.  3.  3. -1.  1.]
 [-1. -1.  1. -3.  0. -3. -3. -1. -3. -3.  3. -3. -3.  1. -1.]
 [ 1.  1. -1.  3. -3.  0.  3.  1.  3.  3. -3.  3.  3. -1.  1.]
 [ 1.  1. -1.  3. -3.  3.  0.  1.  3.  3. -3.  3.  3. -1.  1.]
 [-1. -1.  1.  1. -1.  1.  1.  0.  1.  1. -1.  1.  1. -3.  3.]
 [ 1.  1. -1.  3. -3.  3.  3.  1.  0.  3. -3.  3.  3. -1.  1.]
 [ 1.  1. -1.  3. -3.  3.  3.  1.  3.  0. -3.  3.  3. -1.  1.]
 [-1. -1.  1. -3.  3. -3. -3. -1. -3. -3.  0. -3. -3.  1. -1.]
 [ 1.  1. -1.  3. -3.  3.  3.  1.  3.  3. -3.  0.  3. -1.  1.]
 [ 1.  1. -1.  3. -3.  3.  3.  1.  3.  3. -3.  3.  0. -1.  1.]
 [ 1.  1. -1. -1.  1. -1. -1. -3. -1. -1.  1. -1. -1.  0. -3.]
 [-1. -1.  1.  1. -1.  1.  1.  3.  1.  1. -1.  1.  1. -3.  0.]]


In [ ]:
#Test the convergence of the network

print("------Hopfield network for A----------")
print("input for A", input_A)
while not check_convergence(input_A, weights):
    input_A = update_pattern(input_A, weights)
output_pattern_A = input_A.copy()

print("Final pattern:", output_pattern_A)
print("Energy of the final pattern:", energy(output_pattern_A, weights))
print("Energy of the initial pattern:", energy(input_A, weights))

------Hopfield network for A----------
input for A [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern did not converge to a stable state, repeat another iteration
Pattern converged to a stable state
Final pattern: [ 1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Energy of the final pattern: -163.0
Energy of the initial pattern: -163.0


In [ ]:
print("------Hopfield network for D----------")
print("input for D", input_D)
while not check_convergence(input_D, weights):
    input_D = update_pattern(input_D, weights)
output_pattern_D = input_D.copy()

print("Final pattern:", output_pattern_D)
print("Energy of the final pattern:", energy(output_pattern_D, weights))
print("Energy of the initial pattern:", energy(input_D, weights))

------Hopfield network for D----------
input for D [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
Pattern converged to a stable state
Final pattern: [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
Energy of the final pattern: -127.0
Energy of the initial pattern: -127.0


In [ ]:
print("input for H", input_H)
while not check_convergence(input_H, weights):
    input_H = update_pattern(input_H, weights)
output_pattern_H = input_H.copy()

print("Final pattern:", output_pattern_H)
print("Energy of the final pattern:", energy(output_pattern_H, weights))
print("Energy of the initial pattern:", energy(input_H, weights))

input for H [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern did not converge to a stable state, repeat another iteration
Pattern converged to a stable state
Final pattern: [ 1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Energy of the final pattern: -163.0
Energy of the initial pattern: -163.0


In [ ]:
# calculate hamming distance
def hamming_distance(pattern1, pattern2):
    return np.sum(pattern1 != pattern2)

# Test the hamming distance
print("Hamming distance between A and D:", hamming_distance(output_pattern_A, output_pattern_D))
print("Hamming distance between A and H:", hamming_distance(output_pattern_A, output_pattern_H))
print("Hamming distance between D and H:", hamming_distance(output_pattern_D, output_pattern_H))


Hamming distance between A and D: 3
Hamming distance between A and H: 0
Hamming distance between D and H: 3


1. Energy levels drooped from 0 to -4 , this is because the energy levels are decreasing as the pattern converges to a stable state
2. The energy levels are decreasing as the pattern converges, should always drop to -4

In [ ]:
#Test the convergence of the network with corrupted patterns
print("------Hopfield network for A----------")
print("input for A", input_A_corrupted)
while not check_convergence(input_A_corrupted, weights):
    input_A_corrupted = update_pattern(input_A_corrupted, weights)
output_pattern_A_corrupt = input_A_corrupted.copy()

print("Final pattern:", input_A_corrupted)
print("Energy of the final pattern:", energy(output_pattern_A_corrupt, weights))
print("Energy of the initial pattern:", energy(input_A_corrupted, weights))

------Hopfield network for A----------
input for A [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1  1  1]
Pattern did not converge to a stable state, repeat another iteration
Pattern converged to a stable state
Final pattern: [ 1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Energy of the final pattern: -163.0
Energy of the initial pattern: -163.0


In [ ]:
#Test the convergence of the network with corrupted patterns
print("------Hopfield network for D----------")
print("input for D", input_D_corrupted)
while not check_convergence(input_D_corrupted, weights):
    input_D_corrupted = update_pattern(input_D_corrupted, weights)
output_pattern_D_corrupt = input_D_corrupted.copy()

print("Final pattern:", input_D_corrupted)
print("Energy of the final pattern:", energy(output_pattern_D_corrupt, weights))
print("Energy of the initial pattern:", energy(input_D_corrupted, weights))

------Hopfield network for D----------
input for D [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1  1]
Pattern did not converge to a stable state, repeat another iteration
Pattern converged to a stable state
Final pattern: [ 1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Energy of the final pattern: -163.0
Energy of the initial pattern: -163.0


In [ ]:
#Test the convergence of the network with corrupted patterns
print("------Hopfield network for H----------")
print("input for H", input_H_corrupted)
while not check_convergence(input_A_corrupted, weights):
    input_H_corrupted = update_pattern(input_H_corrupted, weights)
output_pattern_H_corrupt = input_H_corrupted.copy()

print("Final pattern:", input_H_corrupted)
print("Energy of the final pattern:", energy(output_pattern_H_corrupt, weights))
print("Energy of the initial pattern:", energy(input_H_corrupted, weights))

------Hopfield network for H----------
input for H [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern converged to a stable state
Final pattern: [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Energy of the final pattern: -143.0
Energy of the initial pattern: -143.0


## What is your conclusion? \
The Hopfield network is able to recall the original patterns with high accuracy. However, when the patterns are corrupted, the network is not able to recall the original patterns. The classification accuracy decreases as the Hamming distance increases. \

Problem 5: Use the bipolar input patterns A, D and H from Project 3.4 (on page 154). \
(a) Create a heteroassociative BAM network and train on these three patterns (15 inputs, and 3 outputs).\
(b) Test the recall on the same three patterns.  What are your conclusions?  How does the BAM performance compare with the Hopfield performance from Problem 4?\
(c) Test the recall of your BAM network using the same set of corrupted A, D, and H patterns in Problem 4 part c.  What are your conclusions?  How does the BAM performance compare with the Hopfield performance?

In [ ]:
# hetroassociative BAM network for input pattern A

input_A  = np.array([-1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1])
target_A = np.array([-1, 1])
weights_A = np.zeros((len(input_A), len(target_A)))


# compute network for input pattern A

for i in range(len(input_A)):
    for j in range(len(target_A)):
        weights_A[i, j] = input_A[i] * target_A[j]

print("Weight matrix for A:\n", weights_A)


netA = input_A @ weights_A # Activation function
print("NetA:", netA)
outputA = np.where(netA < 0, -1, 1)
print("Output:", outputA)

# Test convergence for input pattern A

recall_A = outputA @ weights_A.T
recall_A = np.where(recall_A < 0, -1, 1)
print("Input  A:", input_A)
print("Recall A:", recall_A)
if np.array_equal(input_A, recall_A):
    print("Pattern converged to a stable state.Stop iteration")
else:
    print(" Recall is not same as input, so we try again with another iteration to produce net with input from previous step as recall and weights")




Weight matrix for A:
 [[ 1. -1.]
 [-1.  1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1. -1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [ 1. -1.]
 [-1.  1.]
 [-1.  1.]
 [ 1. -1.]
 [-1.  1.]]
NetA: [-15.  15.]
Output: [-1  1]
Input  A: [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Recall A: [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern converged to a stable state.Stop iteration


In [ ]:
input_D = np.array([1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1])
target_D = np.array([-1, 1, 1])
weights_D = np.zeros((len(input_D), len(target_D)))


# compute network for input pattern A

for i in range(len(input_D)):
    for j in range(len(target_D)):
        weights_D[i, j] = input_D[i] * target_D[j]

print("Weight matrix for D:\n", weights_D)

netD = input_D @ weights_D # Activation function
print("NetD:", netD)
outputD = np.where(netD < 0, -1, 1)
print("Output:", outputD)

# Test convergence for input pattern D

recall_D = outputD @ weights_D.T
recall_D = np.where(recall_D < 0, -1, 1)
print("Input  A:", input_D)
print("Recall A:", recall_D)
if np.array_equal(input_D, recall_D):
    print("Pattern converged to a stable state.Stop iteration")
else:
    print(" Recall is not same as input, so we try again with another iteration to produce net with input from previous step as recall and weights")


Weight matrix for D:
 [[-1.  1.  1.]
 [-1.  1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1.  1.]
 [-1.  1.  1.]
 [ 1. -1. -1.]]
NetD: [-15.  15.  15.]
Output: [-1  1  1]
Input  A: [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
Recall A: [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
Pattern converged to a stable state.Stop iteration


In [ ]:
input_H = np.array([1, -1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1])
target_H = np.array([1, 1, 1])
weights_H = np.zeros((len(input_H), len(target_H)))

# compute network for input pattern H

for i in range(len(input_H)):
    for j in range(len(target_H)):
        weights_H[i, j] = input_H[i] * target_H[j]

print("Weight matrix for H:\n", weights_H)

netH = input_H @ weights_H # Activation function
print("NetH:", netH)
outputH = np.where(netH < 0, -1, 1)
print("Output:", outputH)

# Test convergence for input pattern H

recall_H = outputH @ weights_H.T
recall_H = np.where(recall_H < 0, -1, 1)
print("Input  H:", input_H)
print("Recall H:", recall_H)
if np.array_equal(input_H, recall_H):
    print("Pattern converged to a stable state.Stop iteration")
else:
    print(" Recall is not same as input, so we try again with another iteration to produce net with input from previous step as recall and weights")

Weight matrix for H:
 [[ 1.  1.  1.]
 [-1. -1. -1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [-1. -1. -1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [-1. -1. -1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [-1. -1. -1.]
 [ 1.  1.  1.]]
NetH: [15. 15. 15.]
Output: [1 1 1]
Input  H: [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Recall H: [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern converged to a stable state.Stop iteration


In [ ]:
# input_C  = np.array([-1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, -1, 1, 1])
# target_C = np.array([1, 1])

# weights_C = np.zeros((len(input_C), len(target_C)))

# # compute network for input pattern C
# for i in range(len(input_C)):
#     for j in range(len(target_C)):
#         weights_C[i, j] = input_C[i] * target_C[j]

# print("Weight matrix for C:\n", weights_C)

# corrpurted version of input A
input_A_corrupted = np.array([-1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1])

net_A_corrupt = input_A_corrupted @ weights_A
print("NetACorrupt:", net_A_corrupt)
outputACorrupt = np.where(net_A_corrupt < 0, -1, 1)
print("Output A:", outputACorrupt)

recall_A_Corrupt = outputACorrupt @ weights_A.T
recall_A_Corrupt = np.where(recall_A_Corrupt < 0, -1, 1)
print("Input  A corrupt:", recall_A_Corrupt)
print("Recall A corrupt:", recall_A_Corrupt)
# Test convergence for input pattern C
if np.array_equal(recall_A_Corrupt, recall_A_Corrupt):
    print("Pattern converged to a stable state.Stop iteration")
else:
    print(" Recall A is not same as input A, so we try again with another iteration to produce net with input as recall_C and weights_C")

# net2 = recall_A_Corrupt @ weights_A
# print("NetC:", netC)
# outputC2 = np.where(netC < 0, -1, 1)
# print("Output C:", outputC2)

# recall_C2 = outputC2 @ weights_C.T
# recall_C2 = np.where(recall_C2 < 0, -1, 1)
# print("Input  C:", input_C)
# print("Recall C:", recall_C2)
# # Test convergence for input pattern C
# if np.array_equal(input_C, recall_C2):
#     print("Pattern converged to a stable state.Stop iteration")
# else:
#     print(" Recall C is not same as input C, so we try again with another iteration to produce net with input as recall_C and weights_C")



NetACorrupt: [-13.  13.]
Output A: [-1  1]
Input  A corrupt: [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Recall A corrupt: [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern converged to a stable state.Stop iteration


In [ ]:
# corrpurted version of input D
input_D_corrupted = np.array([1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1])

net_D_corrupt = input_D_corrupted @ weights_D
print("NetDCorrupt:", net_D_corrupt)
outputDCorrupt = np.where(net_D_corrupt < 0, -1, 1)
print("Output D:", outputDCorrupt)

recall_D_Corrupt = outputDCorrupt @ weights_D.T
recall_D_Corrupt = np.where(recall_D_Corrupt < 0, -1, 1)
print("Input  D corrupt:", recall_D_Corrupt)
print("Recall D corrupt:", recall_D_Corrupt)
# Test convergence for input pattern D
if np.array_equal(recall_D_Corrupt, recall_D_Corrupt):
    print("Pattern converged to a stable state.Stop iteration")
else:
    print(" Recall D is not same as input D, so we try again with another iteration to produce net with input as recall_D and weights_D")

NetDCorrupt: [-13.  13.  13.]
Output D: [-1  1  1]
Input  D corrupt: [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
Recall D corrupt: [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
Pattern converged to a stable state.Stop iteration


In [ ]:
# corrpurted version of input H
input_H_corrupted = np.array([1, -1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1])

net_H_corrupt = input_H_corrupted @ weights_H
print("NetHCorrupt:", net_H_corrupt)
outputHCorrupt = np.where(net_H_corrupt < 0, -1, 1)
print("Output H:", outputHCorrupt)

recall_H_Corrupt = outputHCorrupt @ weights_H.T
recall_H_Corrupt = np.where(recall_H_Corrupt < 0, -1, 1)
print("Input  H corrupt:", recall_H_Corrupt)
print("Recall H corrupt:", recall_H_Corrupt)
# Test convergence for input pattern H
if np.array_equal(recall_H_Corrupt, recall_H_Corrupt):
    print("Pattern converged to a stable state.Stop iteration")
else:
    print(" Recall H is not same as input H, so we try again with another iteration to produce net with input as recall_H and weights_H")

NetHCorrupt: [15. 15. 15.]
Output H: [1 1 1]
Input  H corrupt: [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Recall H corrupt: [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
Pattern converged to a stable state.Stop iteration


# What are your conclusions? \
The BAM network is able to recall the original patterns with high accuracy. The BAM performance is better than the Hopfield performance. The BAM network is able to recall the original patterns even when they are corrupted. The classification accuracy decreases as the Hamming distance increases. \